### ISSUE TITLE
python moudle asexor in backend

### ISSUE THREAD

**Issue by zolty87** [izderadicka/mybookshelf2#1]
After building app with docker I'm getting following errors:
```
backend_1   | Traceback (most recent call last):
backend_1   |   File "engine/backend.py", line 6, in <module>
backend_1   |     from asexor.runner import ApplicationRunnerRawSocket
```

I've also checked in container:
```
root@ubuntu:/opt/mybookshelf2/deploy# docker-compose run --rm backend /bin/bash
root@6fc6983f373b:/code# pip3.5 install git+https://github.com/izderadicka/asexor.git
Collecting git+https://github.com/izderadicka/asexor.git
  Cloning https://github.com/izderadicka/asexor.git to /tmp/pip-sgkc8xnh-build
  Requirement already satisfied (use --upgrade to upgrade): asexor==0.3.0 from git+https://github.com/izderadicka/asexor.git in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: cbor>=1.0.0 in /usr/local/lib/python3.5/dist-packages (from asexor==0.3.0)
Requirement already satisfied: ujson>=1.35 in /usr/local/lib/python3.5/dist-packages (from asexor==0.3.0)
Requirement already satisfied: aiohttp>=1.3.2 in /usr/local/lib/python3.5/dist-packages (from asexor==0.3.0)
Requirement already satisfied: aiohttp-cors>=0.5.0 in /usr/local/lib/python3.5/dist-packages (from asexor==0.3.0)
Requirement already satisfied: async-timeout>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.3.2->asexor==0.3.0)
Requirement already satisfied: chardet in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.3.2->asexor==0.3.0)
Requirement already satisfied: yarl>=0.11 in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.3.2->asexor==0.3.0)
Requirement already satisfied: multidict>=3.0.0 in /usr/local/lib/python3.5/dist-packages (from aiohttp>=1.3.2->asexor==0.3.0)
Requirement already satisfied: typing in /usr/local/lib/python3.5/dist-packages (from aiohttp-cors>=0.5.0->asexor==0.3.0)
root@6fc6983f373b:/code# python
python             python2            python2.7          python3            python3.5          python3.5-config   python3.5m         python3.5m-config
root@6fc6983f373b:/code# python3
Python 3.5.2 (default, Jul 17 2016, 17:38:18)
[GCC 4.6.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from asexor.runner import ApplicationRunnerRawSocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'asexor.runner'
>>>
```

**Comment by izderadicka** [comment]
Hi, 
this is an issues in dependencies  -  you have to install older version of asexor.   
Use asexor tagged v0.2.3.
This change in deploy/requirements.txt should fix it
```
git+https://github.com/izderadicka/asexor.git@v0.2.3
```



mybookshelves2 is moving target, so some things might be out of synch with the rest and  cause problems, sorry.

I actually planned to get rid of crossbar router, as it's kind of overkill for such project.   Asexor is now ready, but MBS2 not yet.  So you has to use older asexor.

**Comment by izderadicka** [comment]
I add few commits to make docker deployment work. It still bit sucks,   but should work if following readme instructions in deploy dir (staging mode).
Doesn't make sense to further improve until dependency on crossbar is resolved - e.g. update for new asexor.

**Comment by izderadicka** [comment]
OK new version with current asexor is out. And deployment is revamped -  now init.sh script guides through all deployment so it should be hopefully easy to try MBS2 in Docker now.
