### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Jero2760** [izderadicka/mybookshelf2#3]
Hi, thanks for sharing this great web platform for managing ebooks. I am stocked trying to run it. Error:
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from app import app, db
  File "/code/app/__init__.py", line 29, in <module>
    register_blueprints()
  File "/code/app/__init__.py", line 21, in register_blueprints
    from app.api import bp as api_bp
  File "/code/app/api.py", line 5, in <module>
    import app.schema as schema
  File "/code/app/schema.py", line 3, in <module>
    from flask_marshmallow import Marshmallow
  File "/usr/local/lib/python3.5/dist-packages/flask_marshmallow/__init__.py", line 24, in <module>
    from . import sqla
  File "/usr/local/lib/python3.5/dist-packages/flask_marshmallow/sqla.py", line 13, in <module>
    import marshmallow_sqlalchemy as msqla
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
    from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/schema.py", line 3, in <module>
    from .convert import ModelConverter
  File "/usr/local/lib/python3.5/dist-packages/marshmallow_sqlalchemy/convert.py", line 80
    ):
    ^
SyntaxError: invalid syntax

Same error doing:
docker-compose run --user 501:20 --rm app python3 manage.py create_tables -a -c

Then, I tried docker-compose build, and get this error:

Setting up desktop integration failed with error:
__________________________________________________
	Traceback (most recent call last):
	  File "calibre/linux.py", line 853, in setup_desktop_integration
	  File "calibre/linux.py", line 875, in do_setup_desktop_integration
	  File "calibre/linux.py", line 906, in install_xdg_junk
	  File "calibre/linux.py", line 891, in install_icons
	  File "calibre/linux.py", line 885, in install_single_icon
	  File "subprocess.py", line 359, in check_call
	  File "subprocess.py", line 340, in call
	  File "subprocess.py", line 854, in __init__
	  File "subprocess.py", line 1702, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

At the end, I get 'Successfully built xxx' message and some docker images were created (deploy_client, deploy_bd, deploy_app, deploy_backend) but nothing shown in localhost:9000.

By the way, to get here I initially had to update the following line in Dockerfile:
https://bootstrap.pypa.io/get-pip.py ----> https://bootstrap.pypa.io/3.5/get-pip.py

Any idea on how to move forward on this installation?
Many thanks

**Comment by izderadicka** [comment]
Unfortunately code is bit old - 3 years is now like ages,   so it's possible that some dependencies have outdated.    

To start with I'd pin to exact versions of dependencies -   so in  deploy requirements.txt replace >=  with ==
Same probably for client (in package JSON) , you will see if client builds.

One error is related to calibre -   so maybe try to  get git older version of calibre in Docker-backend.

deploy/init.sh   should run all deployment for docker and docker compose.  But again it might get outdated somewhere. You'll see where it fails.

re nothing on port 9000 -   this is development version of client -  run in gulp watch -   so check client docker container log.  Also instead you can try simple client on port 6006.

Also you can try stage mode with init.sh -   if it works better.

Sorry for inconvenience,   but last time I've tried to deploy this was more then 3 years ago ( I do have and old deployment running here at home), you will just need to try and fix some issues with old dependencies.

**Comment by Jero2760** [comment]
I see, many thanks for your reply. Can you please provide any details on how to update this installation? I would like to help you with this, but I need more information to get started. For instance, is this image the right picture in docker to run the app? any idea on why this command fails? python3 manage.py create_tables -a -c

<img width="554" alt="deploy1" src="https://user-images.githubusercontent.com/4660910/107248792-f2d6bb00-6a32-11eb-83be-1fc3b2600cfa.png">

**Comment by rlmcclain** [comment]
Just found this project and it looked perfect for my needs. Tried to do the docker stage deployment but received numerous warnings and errors and eventually blew up. From the comments above it seems you will not be updating it. Do you know of any similar projects that are currently maintained? Thank you for this project - it really looks nice from the videos and just what I wanted. Best Wishes.

**Comment by izderadicka** [comment]
I have pinned dependencies so now `deploy/init.sh` script  should create working local deployment in docker (worked for me on Ubuntu 18.04 with Docker 20.10 and docker-compose 1.25).

Indeed this is not ideal solution as some dependencies are now bit outdated, but at least it seems to work now. As I'm using it for years I'd like to have possibility to reinstall. However  I do not have plans now to modernize.
